name: invoxi
description: Invoxi - Invoice Generator (Web, iOS-style)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  web: ^0.5.1
  pdf: ^3.11.3
  printing: ^5.13.1
  file_picker: ^8.0.3
  intl: ^0.20.2
  csv: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: false
  assets:
    - assets/i18n/en.json
    - assets/i18n/de.json